{% set name = "napari-math" %}
{% set version = "0.0.1b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-math-{{ version }}.tar.gz
  sha256: 1f882ec11060bb14f3b245421bfc41a4602e25c986bbbe6ac90183576cc18bdc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - napari
    - numpy
    - python >=3.7

test:
  imports:
    - napari_math
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zacsimile/napari-math
  summary: Simple mathematical operations on image, point and surface layers.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
